@startuml

start

:Create an header file;
:Declare 4 external functions for each operation;
:Create different source file for each operation;
:Link all source files with header file;
:Create a main file with global variable, Menu and Switch Cases;
:Link main file with header file;
:Display Menu;
:Declare variable choice;
:Read Choice/

while (choice is not exit) is (Yes)

:Switch Choice;

fork

-> case1 (Addition);
:result <- num1 + num2;

fork again

-> case2 (subtraction);
:Check which number is bigger;
:Then: result <- bignum - smallnum;

fork again

-> case3 (multiplication);
:result <- num1 x num2;

fork again

-> case4 (division);
:Check which number is bigger;
:Then: result <- bignum / smallnum;

end fork

:Display output;
:Read Choice/

end while (No)

stop

@enduml